name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 确保 Node.js 版本与你的项目要求一致

      - name: Install dependencies
        run: npm install

      - name: Build for macOS arm64
        run: |
          cd src
          target=darwin npx electron-builder build --macos --arm64

      - name: Build for macOS x64
        run: |
          cd src
          target=darwin npx electron-builder build --macos --x64

      - name: Upload macOS arm64 artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-arm64
          path: src/dist/*.dmg

      - name: Upload macOS x64 artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-x64
          path: src/dist/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 确保 Node.js 版本与你的项目要求一致

      - name: Install dependencies
        run: npm install

      - name: Build for Windows x64
        run: |
          cd src
          target=win32 npx electron-builder build --win --x64

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x64
          path: src/dist/*.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-arm64
          path: ./macos-arm64

      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-x64
          path: ./macos-x64

      - name: Download Windows artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-x64
          path: ./windows-x64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload macOS arm64 artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-arm64/*.dmg
          asset_name: macos-arm64.dmg
          asset_content_type: application/octet-stream

      - name: Upload macOS x64 artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-x64/*.dmg
          asset_name: macos-x64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Windows artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-x64/*.exe
          asset_name: windows-x64.exe
          asset_content_type: application/octet-stream
